services:
  backend:
    build:
      context: ./backend
    container_name: transcribeops-backend
    ports:
      - "8000:8000"
    environment:
      - LOCAL_STORAGE_DIR=/app/local_storage
    volumes:
      - ./local_storage:/app/local_storage

  worker:
    build:
      context: ./worker
    container_name: transcribeops-worker
    environment:
      - BACKEND_URL=http://backend:8000
      - LOCAL_STORAGE_DIR=/app/local_storage
      - WHISPER_MODEL=tiny
    volumes:
      - ./local_storage:/app/local_storage
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: transcribeops-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://127.0.0.1:8000
    depends_on:
      - backend